/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as WorkBarringtonColeRouteImport } from './routes/work/barrington-cole'
import { Route as WorkEmberOakRouteImport } from './routes/work/ember-oak'
import { Route as WorkIronCombRouteRouteImport } from './routes/work/iron-comb/route'
import { Route as WorkIronCombIndexRouteImport } from './routes/work/iron-comb/index'
import { Route as WorkIronCombAboutRouteImport } from './routes/work/iron-comb/about'
import { Route as WorkIronCombBookRouteImport } from './routes/work/iron-comb/book'
import { Route as WorkIronCombGalleryRouteImport } from './routes/work/iron-comb/gallery'
import { Route as WorkIronCombServicesRouteImport } from './routes/work/iron-comb/services'
import { Route as WorkMeridianRouteRouteImport } from './routes/work/meridian/route'
import { Route as WorkMeridianIndexRouteImport } from './routes/work/meridian/index'
import { Route as WorkMeridianAboutRouteImport } from './routes/work/meridian/about'
import { Route as WorkMeridianContactRouteImport } from './routes/work/meridian/contact'
import { Route as WorkMeridianServicesRouteImport } from './routes/work/meridian/services'
import { Route as WorkMeridianListingsIndexRouteImport } from './routes/work/meridian/listings.index'
import { Route as WorkMeridianListingsSlugRouteImport } from './routes/work/meridian/listings.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkBarringtonColeRoute = WorkBarringtonColeRouteImport.update({
  id: '/work/barrington-cole',
  path: '/work/barrington-cole',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkEmberOakRoute = WorkEmberOakRouteImport.update({
  id: '/work/ember-oak',
  path: '/work/ember-oak',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIronCombRouteRoute = WorkIronCombRouteRouteImport.update({
  id: '/work/iron-comb',
  path: '/work/iron-comb',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIronCombIndexRoute = WorkIronCombIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkIronCombRouteRoute,
} as any)
const WorkIronCombAboutRoute = WorkIronCombAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => WorkIronCombRouteRoute,
} as any)
const WorkIronCombBookRoute = WorkIronCombBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => WorkIronCombRouteRoute,
} as any)
const WorkIronCombGalleryRoute = WorkIronCombGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => WorkIronCombRouteRoute,
} as any)
const WorkIronCombServicesRoute = WorkIronCombServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => WorkIronCombRouteRoute,
} as any)
const WorkMeridianRouteRoute = WorkMeridianRouteRouteImport.update({
  id: '/work/meridian',
  path: '/work/meridian',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkMeridianIndexRoute = WorkMeridianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkMeridianRouteRoute,
} as any)
const WorkMeridianAboutRoute = WorkMeridianAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => WorkMeridianRouteRoute,
} as any)
const WorkMeridianContactRoute = WorkMeridianContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => WorkMeridianRouteRoute,
} as any)
const WorkMeridianServicesRoute = WorkMeridianServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => WorkMeridianRouteRoute,
} as any)
const WorkMeridianListingsIndexRoute =
  WorkMeridianListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => WorkMeridianRouteRoute,
  } as any)
const WorkMeridianListingsSlugRoute =
  WorkMeridianListingsSlugRouteImport.update({
    id: '/listings/$slug',
    path: '/listings/$slug',
    getParentRoute: () => WorkMeridianRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/work/barrington-cole': typeof WorkBarringtonColeRoute
  '/work/ember-oak': typeof WorkEmberOakRoute
  '/work/iron-comb': typeof WorkIronCombRouteRouteWithChildren
  '/work/iron-comb/': typeof WorkIronCombIndexRoute
  '/work/iron-comb/about': typeof WorkIronCombAboutRoute
  '/work/iron-comb/book': typeof WorkIronCombBookRoute
  '/work/iron-comb/gallery': typeof WorkIronCombGalleryRoute
  '/work/iron-comb/services': typeof WorkIronCombServicesRoute
  '/work/meridian': typeof WorkMeridianRouteRouteWithChildren
  '/work/meridian/': typeof WorkMeridianIndexRoute
  '/work/meridian/about': typeof WorkMeridianAboutRoute
  '/work/meridian/contact': typeof WorkMeridianContactRoute
  '/work/meridian/services': typeof WorkMeridianServicesRoute
  '/work/meridian/listings': typeof WorkMeridianListingsIndexRoute
  '/work/meridian/listings/$slug': typeof WorkMeridianListingsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/work/barrington-cole': typeof WorkBarringtonColeRoute
  '/work/ember-oak': typeof WorkEmberOakRoute
  '/work/iron-comb': typeof WorkIronCombIndexRoute
  '/work/iron-comb/about': typeof WorkIronCombAboutRoute
  '/work/iron-comb/book': typeof WorkIronCombBookRoute
  '/work/iron-comb/gallery': typeof WorkIronCombGalleryRoute
  '/work/iron-comb/services': typeof WorkIronCombServicesRoute
  '/work/meridian': typeof WorkMeridianIndexRoute
  '/work/meridian/about': typeof WorkMeridianAboutRoute
  '/work/meridian/contact': typeof WorkMeridianContactRoute
  '/work/meridian/services': typeof WorkMeridianServicesRoute
  '/work/meridian/listings': typeof WorkMeridianListingsIndexRoute
  '/work/meridian/listings/$slug': typeof WorkMeridianListingsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/work/barrington-cole': typeof WorkBarringtonColeRoute
  '/work/ember-oak': typeof WorkEmberOakRoute
  '/work/iron-comb': typeof WorkIronCombRouteRouteWithChildren
  '/work/iron-comb/': typeof WorkIronCombIndexRoute
  '/work/iron-comb/about': typeof WorkIronCombAboutRoute
  '/work/iron-comb/book': typeof WorkIronCombBookRoute
  '/work/iron-comb/gallery': typeof WorkIronCombGalleryRoute
  '/work/iron-comb/services': typeof WorkIronCombServicesRoute
  '/work/meridian': typeof WorkMeridianRouteRouteWithChildren
  '/work/meridian/': typeof WorkMeridianIndexRoute
  '/work/meridian/about': typeof WorkMeridianAboutRoute
  '/work/meridian/contact': typeof WorkMeridianContactRoute
  '/work/meridian/services': typeof WorkMeridianServicesRoute
  '/work/meridian/listings/': typeof WorkMeridianListingsIndexRoute
  '/work/meridian/listings/$slug': typeof WorkMeridianListingsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/work/barrington-cole'
    | '/work/ember-oak'
    | '/work/iron-comb'
    | '/work/iron-comb/'
    | '/work/iron-comb/about'
    | '/work/iron-comb/book'
    | '/work/iron-comb/gallery'
    | '/work/iron-comb/services'
    | '/work/meridian'
    | '/work/meridian/'
    | '/work/meridian/about'
    | '/work/meridian/contact'
    | '/work/meridian/services'
    | '/work/meridian/listings'
    | '/work/meridian/listings/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/work/barrington-cole'
    | '/work/ember-oak'
    | '/work/iron-comb'
    | '/work/iron-comb/about'
    | '/work/iron-comb/book'
    | '/work/iron-comb/gallery'
    | '/work/iron-comb/services'
    | '/work/meridian'
    | '/work/meridian/about'
    | '/work/meridian/contact'
    | '/work/meridian/services'
    | '/work/meridian/listings'
    | '/work/meridian/listings/$slug'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/work/barrington-cole'
    | '/work/ember-oak'
    | '/work/iron-comb'
    | '/work/iron-comb/'
    | '/work/iron-comb/about'
    | '/work/iron-comb/book'
    | '/work/iron-comb/gallery'
    | '/work/iron-comb/services'
    | '/work/meridian'
    | '/work/meridian/'
    | '/work/meridian/about'
    | '/work/meridian/contact'
    | '/work/meridian/services'
    | '/work/meridian/listings/'
    | '/work/meridian/listings/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  WorkBarringtonColeRoute: typeof WorkBarringtonColeRoute
  WorkEmberOakRoute: typeof WorkEmberOakRoute
  WorkIronCombRouteRoute: typeof WorkIronCombRouteRouteWithChildren
  WorkMeridianRouteRoute: typeof WorkMeridianRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/barrington-cole': {
      id: '/work/barrington-cole'
      path: '/work/barrington-cole'
      fullPath: '/work/barrington-cole'
      preLoaderRoute: typeof WorkBarringtonColeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/ember-oak': {
      id: '/work/ember-oak'
      path: '/work/ember-oak'
      fullPath: '/work/ember-oak'
      preLoaderRoute: typeof WorkEmberOakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/iron-comb': {
      id: '/work/iron-comb'
      path: '/work/iron-comb'
      fullPath: '/work/iron-comb'
      preLoaderRoute: typeof WorkIronCombRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/iron-comb/': {
      id: '/work/iron-comb/'
      path: '/'
      fullPath: '/work/iron-comb/'
      preLoaderRoute: typeof WorkIronCombIndexRouteImport
      parentRoute: typeof WorkIronCombRouteRoute
    }
    '/work/iron-comb/about': {
      id: '/work/iron-comb/about'
      path: '/about'
      fullPath: '/work/iron-comb/about'
      preLoaderRoute: typeof WorkIronCombAboutRouteImport
      parentRoute: typeof WorkIronCombRouteRoute
    }
    '/work/iron-comb/book': {
      id: '/work/iron-comb/book'
      path: '/book'
      fullPath: '/work/iron-comb/book'
      preLoaderRoute: typeof WorkIronCombBookRouteImport
      parentRoute: typeof WorkIronCombRouteRoute
    }
    '/work/iron-comb/gallery': {
      id: '/work/iron-comb/gallery'
      path: '/gallery'
      fullPath: '/work/iron-comb/gallery'
      preLoaderRoute: typeof WorkIronCombGalleryRouteImport
      parentRoute: typeof WorkIronCombRouteRoute
    }
    '/work/iron-comb/services': {
      id: '/work/iron-comb/services'
      path: '/services'
      fullPath: '/work/iron-comb/services'
      preLoaderRoute: typeof WorkIronCombServicesRouteImport
      parentRoute: typeof WorkIronCombRouteRoute
    }
    '/work/meridian': {
      id: '/work/meridian'
      path: '/work/meridian'
      fullPath: '/work/meridian'
      preLoaderRoute: typeof WorkMeridianRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/meridian/': {
      id: '/work/meridian/'
      path: '/'
      fullPath: '/work/meridian/'
      preLoaderRoute: typeof WorkMeridianIndexRouteImport
      parentRoute: typeof WorkMeridianRouteRoute
    }
    '/work/meridian/about': {
      id: '/work/meridian/about'
      path: '/about'
      fullPath: '/work/meridian/about'
      preLoaderRoute: typeof WorkMeridianAboutRouteImport
      parentRoute: typeof WorkMeridianRouteRoute
    }
    '/work/meridian/contact': {
      id: '/work/meridian/contact'
      path: '/contact'
      fullPath: '/work/meridian/contact'
      preLoaderRoute: typeof WorkMeridianContactRouteImport
      parentRoute: typeof WorkMeridianRouteRoute
    }
    '/work/meridian/services': {
      id: '/work/meridian/services'
      path: '/services'
      fullPath: '/work/meridian/services'
      preLoaderRoute: typeof WorkMeridianServicesRouteImport
      parentRoute: typeof WorkMeridianRouteRoute
    }
    '/work/meridian/listings/': {
      id: '/work/meridian/listings/'
      path: '/listings'
      fullPath: '/work/meridian/listings'
      preLoaderRoute: typeof WorkMeridianListingsIndexRouteImport
      parentRoute: typeof WorkMeridianRouteRoute
    }
    '/work/meridian/listings/$slug': {
      id: '/work/meridian/listings/$slug'
      path: '/listings/$slug'
      fullPath: '/work/meridian/listings/$slug'
      preLoaderRoute: typeof WorkMeridianListingsSlugRouteImport
      parentRoute: typeof WorkMeridianRouteRoute
    }
  }
}

interface WorkIronCombRouteRouteChildren {
  WorkIronCombIndexRoute: typeof WorkIronCombIndexRoute
  WorkIronCombAboutRoute: typeof WorkIronCombAboutRoute
  WorkIronCombBookRoute: typeof WorkIronCombBookRoute
  WorkIronCombGalleryRoute: typeof WorkIronCombGalleryRoute
  WorkIronCombServicesRoute: typeof WorkIronCombServicesRoute
}

const WorkIronCombRouteRouteChildren: WorkIronCombRouteRouteChildren = {
  WorkIronCombIndexRoute: WorkIronCombIndexRoute,
  WorkIronCombAboutRoute: WorkIronCombAboutRoute,
  WorkIronCombBookRoute: WorkIronCombBookRoute,
  WorkIronCombGalleryRoute: WorkIronCombGalleryRoute,
  WorkIronCombServicesRoute: WorkIronCombServicesRoute,
}

const WorkIronCombRouteRouteWithChildren =
  WorkIronCombRouteRoute._addFileChildren(WorkIronCombRouteRouteChildren)

interface WorkMeridianRouteRouteChildren {
  WorkMeridianIndexRoute: typeof WorkMeridianIndexRoute
  WorkMeridianAboutRoute: typeof WorkMeridianAboutRoute
  WorkMeridianContactRoute: typeof WorkMeridianContactRoute
  WorkMeridianServicesRoute: typeof WorkMeridianServicesRoute
  WorkMeridianListingsIndexRoute: typeof WorkMeridianListingsIndexRoute
  WorkMeridianListingsSlugRoute: typeof WorkMeridianListingsSlugRoute
}

const WorkMeridianRouteRouteChildren: WorkMeridianRouteRouteChildren = {
  WorkMeridianIndexRoute: WorkMeridianIndexRoute,
  WorkMeridianAboutRoute: WorkMeridianAboutRoute,
  WorkMeridianContactRoute: WorkMeridianContactRoute,
  WorkMeridianServicesRoute: WorkMeridianServicesRoute,
  WorkMeridianListingsIndexRoute: WorkMeridianListingsIndexRoute,
  WorkMeridianListingsSlugRoute: WorkMeridianListingsSlugRoute,
}

const WorkMeridianRouteRouteWithChildren =
  WorkMeridianRouteRoute._addFileChildren(WorkMeridianRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  WorkBarringtonColeRoute: WorkBarringtonColeRoute,
  WorkEmberOakRoute: WorkEmberOakRoute,
  WorkIronCombRouteRoute: WorkIronCombRouteRouteWithChildren,
  WorkMeridianRouteRoute: WorkMeridianRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
